### ISSUE TITLE
TIFF

### ISSUE THREAD

**Issue by sarayar** [camicroscope/SlideLoader#18]
I had no problem uploading SVS but can we upload TIFF slides?

**Comment by birm** [comment]
Hello,
Currently, we have set the uploader to only allow .svs and .tif as extensions (https://github.com/camicroscope/SlideLoader/blob/44c3ec71669b70db483c07f9b3efc5347ce72810/SlideServer.py#L29). The utility should, however, be able to read any openslide compatible format (see https://openslide.org/)

We can add support for more/all of these extensions in the future, but in the mean time, if you need help uploading some files, please let me know, and I'd be happy to help.

**Comment by birm** [comment]
@sarayar Just for clarification, what is the file extension you're using, and what is the error reported to you, if any?

**Comment by birm** [comment]
I've added support for tiff in https://github.com/camicroscope/SlideLoader/commit/1eb36af700449176e9119313cc725990dedb3235
