### ISSUE TITLE
Seperate token security for SlideLoader as proxy is not completely secure

### ISSUE THREAD

**Issue by Vedant1202** [camicroscope/SlideLoader#27]
**Is your feature request related to a problem? Please describe.**
The ip of the SlideLoader container stays unprotected even if the Caracal proxy has token checking. This secures the requests coming from the camicroscope client however, it does not secure the endpoints from attacks directly to the container's IP. 

![Screencast-from-Thursday-09-April-2020-02_04_10-IST](https://user-images.githubusercontent.com/35070972/78876226-a3b7a680-7a6c-11ea-9210-c96efb7cbbb1.gif)

Like this example where the unprotected route for deleting slide on slideloader is being hit outside of the client by using it's IP instead of the proxy url. The slide 'sample.svs' gets deleted even though no tokenisation is perfomed.

Such attacks are common on proxies and thus each individual server having their own token checking mechanism proves is better for additional security.

_Note that unprotected here means the route has no seperate token checker. Other security measures in caracal are in place and have been configured to be active_

**Describe the solution you'd like**
Seperate token security functions and handlers to secure the loader container.
An initial solution is requested in [PR-25](https://github.com/camicroscope/SlideLoader/pull/25)

**Comment by birm** [comment]
What kind of deployment would this be a problem with; I don't think the docker internal network is visible to other hosts unless explicitly routed, right?

**Comment by birm** [comment]
I think so. Thanks for keeping an eye on security!
