### ISSUE TITLE
NCI's post slide is called incorrectly

### ISSUE THREAD

**Issue by birm** [camicroscope/SlideLoader#56]
https://github.com/camicroscope/SlideLoader/blob/4c8722a269d75e78215a7b4d47b8ad9089bb7ca3/NCISlideUtil.py#L28

post_slide does not take an api key, and will fail if you try to call it this way

**Comment by samO2I1** [comment]
@birm I am new to Google Summer Of Code . Can I work on this issue ?

**Comment by birm** [comment]
if you like!
